const C=[
[1,18.0,'TURN 1 — BRAKE'],[2,22.2,'TURN 2 — LEFT'],[3,25,'TURN 3 — RIGHT'],[4,28.2,'TURN 4 — LEFT'],[5,31.2,'TURN 5 — RIGHT'],[6,34.8,'TURN 6 — LEFT'],[7,38,'TURN 7 — RIGHT'],[8,42,'TURN 8 — LEFT'],[9,45.5,'TURN 9 — RIGHT'],[10,50.5,'TURN 10 — BRAKE'],[11,54,'TURN 11 — LEFT'],[12,59,'TURN 12 — RIGHT'],[13,64,'TURN 13 — LEFT'],[14,69,'TURN 14 — RIGHT'],[15,74,'TURN 15 — LEFT'],[16,82,'TURN 16 — RIGHT'],[17,86,'TURN 17 — LEFT'],[18,94,'TURN 18 — RIGHT'],[19,99,'TURN 19 — RIGHT'],[20,105,'LAP COMPLETE']];
const names={105:'1:45',106:'1:46',107:'1:47',108:'1:48'};let target=105,running=false,start=0,i=0,raf;
const $=x=>document.getElementById(x);function speak(t){if(!speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.rate=1.1;u.pitch=.9;speechSynthesis.speak(u)}
function scale(t){return t*target/105}function fmt(s){let m=Math.floor(s/60);return `${m}:${(s-m*60).toFixed(1).padStart(4,'0')}`}
function reset(){ $('target').textContent=names[target];$('call').textContent='READY';$('next').textContent='Press START when you\'re ready.';$('lap').textContent='0:00.0';$('count').textContent='--';$('corner').textContent='—'}
function stop(){running=false;cancelAnimationFrame(raf);speechSynthesis?.cancel();$('status').textContent='STOPPED';$('next').textContent='Lap stopped. Press START to run again.'}
function tick(now){if(!running)return;let e=(now-start)/1000;$('lap').textContent=fmt(e);while(i<C.length&&e>=scale(C[i][1])){let c=C[i++];$('call').textContent=c[2];$('corner').textContent=c[0]===20?'FINISH':c[0];speak(c[2])}if(i<C.length){let r=Math.max(0,scale(C[i][1])-e);$('count').textContent=r.toFixed(1)+'s';$('next').textContent=C[i][2]}if(e>=target){running=false;$('status').textContent='LAP COMPLETE';$('call').textContent='LAP COMPLETE';$('next').textContent='Target lap reached.';return}raf=requestAnimationFrame(tick)}
function startLap(){if(running)return; speechSynthesis?.cancel();running=true;i=0;start=performance.now();$('status').textContent='LIVE';$('call').textContent='GO GO GO';$('next').textContent=C[0][2];speak('Go go go');raf=requestAnimationFrame(tick)}
document.querySelectorAll('.paces button').forEach(b=>b.onclick=()=>{if(!running){target=+b.dataset.lap;document.querySelectorAll('.paces button').forEach(x=>x.classList.toggle('selected',x===b));reset()}});$('start').onclick=startLap;$('stop').onclick=stop;$('test').onclick=()=>speak('Race engineer audio check. Turn one. Brake.');document.querySelector('.paces button').classList.add('selected');reset();
